### ISSUE TITLE
Failed to load the animation-showcase package

### ISSUE THREAD

**Issue by christianwensel** [mafiuss/atom-animation-showcase#6]
[Enter steps to reproduce below:]
1. updated atom to 1.1.0

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [animation-showcase](https://github.com/mafiuss/atom-animation-showcase) package, v0.7.3
### Stack Trace

Failed to load the animation-showcase package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/xian/.atom/packages/animation-showcase/lib/threejs-examples-view.coffee:1:1)
    at /Users/xian/.atom/packages/animation-showcase/lib/threejs-examples-view.coffee:6:3
    at Object.<anonymous> (/Users/xian/.atom/packages/animation-showcase/lib/threejs-examples-view.coffee:6:3)
    at Object.<anonymous> (/Users/xian/.atom/packages/animation-showcase/lib/threejs-examples-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "railscast-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
animation-showcase, v0.7.3
minimap, v4.16.0
pretty-json, v0.4.1
railscast-theme, v0.3.0
ruby-slim, v0.2.0
seti-ui, v0.8.1
threejs-snippets, v0.0.8

# Dev
No dev packages
```

**Comment by christianwensel** [comment]
please close if redundant or if not helpful if you have any followup questions lmk

**Comment by mafiuss** [comment]
Thanks for the report, will take a look, it´s been several atom versions since I last visited this package no surprise something got broken. :+1:

**Comment by christianwensel** [comment]
5y closing.
