### ISSUE TITLE
Failed to load the animation-showcase package

### ISSUE THREAD

**Issue by implict** [mafiuss/atom-animation-showcase#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.10.2
**Thrown From**: [animation-showcase](https://github.com/mafiuss/atom-animation-showcase) package, v0.7.3
### Stack Trace

Failed to load the animation-showcase package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/jiwonpark/.atom/packages/animation-showcase/lib/threejs-examples-view.coffee:1:1)
    at /Users/jiwonpark/.atom/packages/animation-showcase/lib/threejs-examples-view.coffee:6:3
    at Object.<anonymous> (/Users/jiwonpark/.atom/packages/animation-showcase/lib/threejs-examples-view.coffee:6:3)
    at Object.<anonymous> (/Users/jiwonpark/.atom/packages/animation-showcase/lib/threejs-examples-view.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "processing",
      "block-comment",
      "fold-comments"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
animation-showcase, v0.7.3
atom-alignment, v0.12.1
atom-html-preview, v0.1.11
atom-jade, v0.3.0
browser-plus, v0.0.34
emmet, v2.3.12
processing-language, v0.2.0
selector-to-tag, v0.4.1
terminal-plus, v0.11.1

# Dev
No dev packages
```

**Comment by danieltarazona** [comment]
The SAME Err.

**Comment by JackGuoFranklin** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.3
**Thrown From**: [animation-showcase](https://github.com/mafiuss/atom-animation-showcase) package, v0.7.3

### Stack Trace

Failed to load the animation-showcase package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/guojunbing23/.atom/packages/animation-showcase/lib/threejs-examples-view.coffee:1:1)
    at /Users/guojunbing23/.atom/packages/animation-showcase/lib/threejs-examples-view.coffee:6:3
    at Object.<anonymous> (/Users/guojunbing23/.atom/packages/animation-showcase/lib/threejs-examples-view.coffee:6:3)
    at Object.<anonymous> (/Users/guojunbing23/.atom/packages/animation-showcase/lib/threejs-examples-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/guojunbing23/.atom/packages/animation-showcase/lib/threejs-examples.coffee:1:23)
    at Object.<anonymous> (/Users/guojunbing23/.atom/packages/animation-showcase/lib/threejs-examples.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
animation-showcase, v0.7.3
autocomplete-swift, v1.0.2
language-swift, v0.4.0
threejs-snippets, v0.0.8
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by trusktr** [comment]
Dang, wanted to try this package, but get this error when activating the package.
